services:
  db:
    image: postgres:15
    container_name: task_pg
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: jt
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/migrations
    restart: always

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command:
      [
        '-path=/migrations',
        '-database=postgres://jt:secret@db:5432/tasks_db?sslmode=disable',
        'up',
      ]
    restart: 'on-failure'

volumes:
  pgdata:
