version: '3.8'

services:
  db:
    image: postgres:15
    container_name: task_pg
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: jt
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
