services:
  db:
    image: postgres:15
    container_name: task_pg
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: jt
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/migrations
    restart: always

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command:
      [
        '-path=/migrations',
        '-database=postgres://jt:secret@db:5432/tasks_db?sslmode=disable',
        'up',
      ]
    restart: 'on-failure'

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: jt
      DB_PASSWORD: secret
      DB_NAME: tasks_db
      DB_DRIVER: postgres
    env_file:
      - .env
volumes:
  pgdata:
